/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisplayTeriasmaton.java
 *
 * Created on 17 Ιαν 2012, 10:37:47 πμ
 */
package basics;

import java.sql.Time;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Administrator
 */
public class EbresiEnosAitimatos extends javax.swing.JFrame {

    /** Creates new form DisplayTeriasmaton */
    String[] hmeres = {"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31"};    
    String[] mhnes = {"1","2","3","4","5","6","7","8","9","10","11","12"};
    String[] xronia = {"2011","2012","2013","2014","2015","2016"};
    String[] nora = {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24"};
    String[] nlepta = {"00","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60"};
    String[] aora = {"01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24"};
    String[] alepta = {"00","01","02","03","04","05","06","07","08","09","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49","50","51","52","53","54","55","56","57","58","59","60"};
    
    DefaultComboBoxModel hmeresbox;
    DefaultComboBoxModel mhnesbox;
    DefaultComboBoxModel xroniabox;
    DefaultComboBoxModel norabox;
    DefaultComboBoxModel nleptabox;
    DefaultComboBoxModel aorabox;
    DefaultComboBoxModel aleptabox;
    
    
    public EbresiEnosAitimatos() {
        hmeresbox = new DefaultComboBoxModel(hmeres);
        mhnesbox = new DefaultComboBoxModel(mhnes);
        xroniabox = new DefaultComboBoxModel(xronia);
        norabox = new DefaultComboBoxModel(nora);
        nleptabox = new DefaultComboBoxModel(nlepta);
        aorabox = new DefaultComboBoxModel(aora);
        aleptabox = new DefaultComboBoxModel(alepta);
        
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Earlydepora = new javax.swing.JComboBox();
        Earlydep = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        Depdatexronia = new javax.swing.JComboBox();
        Latedep = new javax.swing.JLabel();
        Latedeplepta = new javax.swing.JComboBox();
        Latedepora = new javax.swing.JComboBox();
        Cancel = new javax.swing.JButton();
        Cityend = new javax.swing.JLabel();
        CitystartText = new javax.swing.JTextField();
        Depdate = new javax.swing.JLabel();
        CityendText = new javax.swing.JTextField();
        Citystart = new javax.swing.JLabel();
        Depdatemera = new javax.swing.JComboBox();
        Numbppl = new javax.swing.JLabel();
        Earlydeplepta = new javax.swing.JComboBox();
        NumbpplText = new javax.swing.JTextField();
        Depdatemin = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ebresi enos teriasmatos");

        jLabel1.setText("Dose mou ena aitima gia na emfaniso tis prosfores pou iparxoun");

        Earlydepora.setModel(norabox);

        Earlydep.setText("Noriteri ora anax.");

        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        Depdatexronia.setModel(xroniabox);

        Latedep.setText("Argoteri ora anax.");

        Latedeplepta.setModel(aleptabox);

        Latedepora.setModel(aorabox);

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        Cityend.setText("Teliki poli");

        Depdate.setText("Hmera anax.");

        Citystart.setText("Arxiki poli");

        Depdatemera.setModel(hmeresbox);
        Depdatemera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepdatemeraActionPerformed(evt);
            }
        });

        Numbppl.setText("Arithmos atomon");

        Earlydeplepta.setModel(nleptabox);

        Depdatemin.setModel(mhnesbox);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(OK)
                        .addGap(115, 115, 115)
                        .addComponent(Cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Citystart)
                            .addComponent(Cityend)
                            .addComponent(Depdate)
                            .addComponent(Earlydep)
                            .addComponent(Latedep)
                            .addComponent(Numbppl))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CityendText)
                                .addComponent(CitystartText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NumbpplText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Depdatemera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Earlydepora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Latedepora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Earlydeplepta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Depdatemin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(59, 59, 59)
                                        .addComponent(Depdatexronia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Latedeplepta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Citystart)
                    .addComponent(CitystartText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cityend)
                    .addComponent(CityendText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Depdate)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Depdatemera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Depdatexronia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Depdatemin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Earlydep)
                    .addComponent(Earlydepora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Earlydeplepta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(Latedep))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Latedepora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Latedeplepta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numbppl)
                    .addComponent(NumbpplText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK)
                    .addComponent(Cancel))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
// TODO add your handling code here:
    String citystart = CitystartText.getText();
    String cityend = CityendText.getText();
    
    String d = (String)Depdatemera.getSelectedItem();
    int day = new Integer(d).intValue();
    
    String m = (String)Depdatemin.getSelectedItem();
    int month = new Integer(m).intValue();
    
    String y = (String)Depdatexronia.getSelectedItem();
    int year = new Integer(y).intValue();
    
    Date depdate = new Date(day,month,year);
    
    String eh = (String)Earlydepora.getSelectedItem();
    int ehour = new Integer(eh).intValue();
    
    String el = (String)Earlydeplepta.getSelectedItem();
    int emin = new Integer(el).intValue();
    
    Time earlydep = new Time(ehour,emin,0);
    
    String lh = (String)Latedepora.getSelectedItem();
    int lhour = new Integer(lh).intValue();
    
    String ll = (String)Latedeplepta.getSelectedItem();
    int lmin = new Integer(ll).intValue();
    
    Time latedep = new Time(lhour,lmin,0);
    
    String numbppl = NumbpplText.getText();
    
    
    Route r = new Route(citystart, cityend, depdate, earlydep, latedep,null);
    
    Request re = new Request(r,numbppl);
    
    Demo3.monorequest.add(re);
    
    DisplayTeriasmaton dt = new DisplayTeriasmaton();
    dt.setVisible(true);
    this.dispose();
    
}//GEN-LAST:event_OKActionPerformed

private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
// TODO add your handling code here:
    this.dispose();
}//GEN-LAST:event_CancelActionPerformed

private void DepdatemeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepdatemeraActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_DepdatemeraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EbresiEnosAitimatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EbresiEnosAitimatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EbresiEnosAitimatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EbresiEnosAitimatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new EbresiEnosAitimatos().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel Cityend;
    private javax.swing.JTextField CityendText;
    private javax.swing.JLabel Citystart;
    private javax.swing.JTextField CitystartText;
    private javax.swing.JLabel Depdate;
    private javax.swing.JComboBox Depdatemera;
    private javax.swing.JComboBox Depdatemin;
    private javax.swing.JComboBox Depdatexronia;
    private javax.swing.JLabel Earlydep;
    private javax.swing.JComboBox Earlydeplepta;
    private javax.swing.JComboBox Earlydepora;
    private javax.swing.JLabel Latedep;
    private javax.swing.JComboBox Latedeplepta;
    private javax.swing.JComboBox Latedepora;
    private javax.swing.JLabel Numbppl;
    private javax.swing.JTextField NumbpplText;
    private javax.swing.JButton OK;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
