/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Menu.java
 *
 * Created on 12 Ιαν 2012, 9:31:05 πμ
 */
package basics;

import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class Menu extends javax.swing.JFrame {

    /** Creates new form Menu */
    public Menu() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NeaProsfora = new javax.swing.JLabel();
        NeaProsforaButton = new javax.swing.JButton();
        NeoAitima = new javax.swing.JLabel();
        NeoAitimaButton = new javax.swing.JButton();
        DisplayProsforon = new javax.swing.JLabel();
        DisplayProsforonButton = new javax.swing.JButton();
        DisplayAitimaton = new javax.swing.JLabel();
        DisplayAitimatonButton = new javax.swing.JButton();
        RArxioProsforon = new javax.swing.JLabel();
        RArxioProsforonButton = new javax.swing.JButton();
        RArxioAitimaton = new javax.swing.JLabel();
        RArxioAitimatonButton = new javax.swing.JButton();
        WArxioProsforon = new javax.swing.JLabel();
        WArxioProsforonButton = new javax.swing.JButton();
        WArxioAitimaton = new javax.swing.JLabel();
        WArxioAitimatonButton = new javax.swing.JButton();
        EbresikeEmfanisi = new javax.swing.JLabel();
        EbresikeEmfanisiButton = new javax.swing.JButton();
        WArxioTeriasmaton = new javax.swing.JLabel();
        WArxioTeriasmatonButton = new javax.swing.JButton();
        Exit = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        DipslayTeriasma = new javax.swing.JLabel();
        DipslayTeriasmaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basiko Menu");

        NeaProsfora.setText("Gia kataxorisi neas prosforas patiste dipla");

        NeaProsforaButton.setText("Nea Prosfora");
        NeaProsforaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeaProsforaButtonActionPerformed(evt);
            }
        });

        NeoAitima.setText("Gia kataxorisi neou aitimatos patiste dipla");

        NeoAitimaButton.setText("Neo Aitima");
        NeoAitimaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NeoAitimaButtonActionPerformed(evt);
            }
        });

        DisplayProsforon.setText("Gia emfanisi olon ton prosforon patiste dipla");

        DisplayProsforonButton.setText("Display Prosforon");
        DisplayProsforonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayProsforonButtonActionPerformed(evt);
            }
        });

        DisplayAitimaton.setText("Gia emfanisi olon ton aitimaton patiste dipla");

        DisplayAitimatonButton.setText("Display Aitimaton");
        DisplayAitimatonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayAitimatonButtonActionPerformed(evt);
            }
        });

        RArxioProsforon.setText("Gia na anaktisete prosfores apo ena arxio patiste dipla");

        RArxioProsforonButton.setText("R.Arxio Prosforon");
        RArxioProsforonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RArxioProsforonButtonActionPerformed(evt);
            }
        });

        RArxioAitimaton.setText("Gia na anaktisete aitimata apo ena arxio patiste dipla");

        RArxioAitimatonButton.setText("R.Arxio Aitimaton");
        RArxioAitimatonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RArxioAitimatonButtonActionPerformed(evt);
            }
        });

        WArxioProsforon.setText("Gia na sosete tis prosfores se ena arxio patiste dipla");

        WArxioProsforonButton.setText("W.Arxio Prosforon");
        WArxioProsforonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WArxioProsforonButtonActionPerformed(evt);
            }
        });

        WArxioAitimaton.setText("Gia na sosete ta aitimata se ena arxio patiste dipla");

        WArxioAitimatonButton.setText("W.Arxio Aitimaton");
        WArxioAitimatonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WArxioAitimatonButtonActionPerformed(evt);
            }
        });

        EbresikeEmfanisi.setText("Gia ebresi ke emfanisi teriasmaton aitimaton patiste dipla");

        EbresikeEmfanisiButton.setText("Teriasmata");
        EbresikeEmfanisiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EbresikeEmfanisiButtonActionPerformed(evt);
            }
        });

        WArxioTeriasmaton.setText("Gia apothikeusi ton teriasmaton se arxio patiste dipla");

        WArxioTeriasmatonButton.setText("W.Arxio Teriasmaton");
        WArxioTeriasmatonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WArxioTeriasmatonButtonActionPerformed(evt);
            }
        });

        Exit.setText("Gia na klisete to programma patiste dipla");

        ExitButton.setText("EXIT");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        DipslayTeriasma.setText("Gia emfanisi prosforon pou teriazoun se ena aitima patiste dipla");

        DipslayTeriasmaButton.setText("Ena Teriasma");
        DipslayTeriasmaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DipslayTeriasmaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NeaProsfora)
                                .addComponent(NeoAitima)
                                .addComponent(DisplayProsforon)
                                .addComponent(DisplayAitimaton)
                                .addComponent(RArxioProsforon)
                                .addComponent(RArxioAitimaton)
                                .addComponent(WArxioProsforon)
                                .addComponent(WArxioAitimaton)
                                .addComponent(WArxioTeriasmaton)
                                .addComponent(Exit))
                            .addGap(43, 43, 43))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(EbresikeEmfanisi, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DipslayTeriasma)
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DipslayTeriasmaButton)
                    .addComponent(ExitButton)
                    .addComponent(NeoAitimaButton)
                    .addComponent(NeaProsforaButton)
                    .addComponent(DisplayProsforonButton)
                    .addComponent(DisplayAitimatonButton)
                    .addComponent(RArxioProsforonButton)
                    .addComponent(RArxioAitimatonButton)
                    .addComponent(WArxioProsforonButton)
                    .addComponent(WArxioAitimatonButton)
                    .addComponent(EbresikeEmfanisiButton)
                    .addComponent(WArxioTeriasmatonButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NeaProsfora)
                    .addComponent(NeaProsforaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NeoAitima)
                    .addComponent(NeoAitimaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisplayProsforon)
                    .addComponent(DisplayProsforonButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisplayAitimaton)
                    .addComponent(DisplayAitimatonButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RArxioProsforon)
                    .addComponent(RArxioProsforonButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RArxioAitimaton)
                    .addComponent(RArxioAitimatonButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WArxioProsforon)
                    .addComponent(WArxioProsforonButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WArxioAitimaton)
                    .addComponent(WArxioAitimatonButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DipslayTeriasma)
                    .addComponent(DipslayTeriasmaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EbresikeEmfanisiButton)
                    .addComponent(EbresikeEmfanisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WArxioTeriasmaton)
                    .addComponent(WArxioTeriasmatonButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Exit)
                    .addComponent(ExitButton))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void NeaProsforaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeaProsforaButtonActionPerformed
// TODO add your handling code here:
    JRoute j = new JRoute();
    j.setVisible(true);
}//GEN-LAST:event_NeaProsforaButtonActionPerformed

private void NeoAitimaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NeoAitimaButtonActionPerformed
// TODO add your handling code here:
    JRequest r = new JRequest();
    r.setVisible(true);
}//GEN-LAST:event_NeoAitimaButtonActionPerformed

private void DisplayProsforonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayProsforonButtonActionPerformed
// TODO add your handling code here:
    DisplayOffer od = new DisplayOffer();
    od.setVisible(true);
}//GEN-LAST:event_DisplayProsforonButtonActionPerformed

private void DisplayAitimatonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayAitimatonButtonActionPerformed
// TODO add your handling code here:
    DisplayRequest rd = new DisplayRequest();
    rd.setVisible(true);
}//GEN-LAST:event_DisplayAitimatonButtonActionPerformed

private void RArxioProsforonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RArxioProsforonButtonActionPerformed
// TODO add your handling code here:
    RArxioProsforon rof = new RArxioProsforon();
    rof.setVisible(true);
}//GEN-LAST:event_RArxioProsforonButtonActionPerformed

private void RArxioAitimatonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RArxioAitimatonButtonActionPerformed
// TODO add your handling code here:
    RArxioAitimaton rre = new RArxioAitimaton();
    rre.setVisible(true);
}//GEN-LAST:event_RArxioAitimatonButtonActionPerformed

private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
    // TODO add your handling code here:
    int n = JOptionPane.showConfirmDialog(null,"Are you sure?","ConfirmDialog",JOptionPane.YES_NO_OPTION);
    if(n==0){
        System.exit(0);
    }
    
}//GEN-LAST:event_ExitButtonActionPerformed

private void WArxioProsforonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WArxioProsforonButtonActionPerformed
    // TODO add your handling code here:
    WArxioProsforon wof = new WArxioProsforon();
    wof.setVisible(true);
}//GEN-LAST:event_WArxioProsforonButtonActionPerformed

private void WArxioAitimatonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WArxioAitimatonButtonActionPerformed
    // TODO add your handling code here:
    WArxioAitimaton wre = new WArxioAitimaton();
    wre.setVisible(true);
}//GEN-LAST:event_WArxioAitimatonButtonActionPerformed

private void DipslayTeriasmaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DipslayTeriasmaButtonActionPerformed
// TODO add your handling code here:
    EbresiEnosAitimatos eet = new EbresiEnosAitimatos();
    eet.setVisible(true);
}//GEN-LAST:event_DipslayTeriasmaButtonActionPerformed

private void EbresikeEmfanisiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EbresikeEmfanisiButtonActionPerformed
// TODO add your handling code here:
    EbresiKeEmfanisiTeriasmaton et = new EbresiKeEmfanisiTeriasmaton();
    et.setVisible(true);
}//GEN-LAST:event_EbresikeEmfanisiButtonActionPerformed

private void WArxioTeriasmatonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WArxioTeriasmatonButtonActionPerformed
// TODO add your handling code here:
    WArxioTeriasmaton wat = new WArxioTeriasmaton();
    wat.setVisible(true);
}//GEN-LAST:event_WArxioTeriasmatonButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DipslayTeriasma;
    private javax.swing.JButton DipslayTeriasmaButton;
    private javax.swing.JLabel DisplayAitimaton;
    private javax.swing.JButton DisplayAitimatonButton;
    private javax.swing.JLabel DisplayProsforon;
    private javax.swing.JButton DisplayProsforonButton;
    private javax.swing.JLabel EbresikeEmfanisi;
    private javax.swing.JButton EbresikeEmfanisiButton;
    private javax.swing.JLabel Exit;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel NeaProsfora;
    private javax.swing.JButton NeaProsforaButton;
    private javax.swing.JLabel NeoAitima;
    private javax.swing.JButton NeoAitimaButton;
    private javax.swing.JLabel RArxioAitimaton;
    private javax.swing.JButton RArxioAitimatonButton;
    private javax.swing.JLabel RArxioProsforon;
    private javax.swing.JButton RArxioProsforonButton;
    private javax.swing.JLabel WArxioAitimaton;
    private javax.swing.JButton WArxioAitimatonButton;
    private javax.swing.JLabel WArxioProsforon;
    private javax.swing.JButton WArxioProsforonButton;
    private javax.swing.JLabel WArxioTeriasmaton;
    private javax.swing.JButton WArxioTeriasmatonButton;
    // End of variables declaration//GEN-END:variables
}
